### ISSUE TITLE
`mocha` needs installing?

### ISSUE THREAD

**Issue by spences10** [MarcL/js-unit-testing-framework#1]
Is this something that you go over in the course?

Or do I need to add it to the `package.json`?

![image](https://cloud.githubusercontent.com/assets/234708/25910162/62d94ea0-35a7-11e7-84c5-9652873c7b07.png)

**Comment by MarcL** [comment]
Oh! Sorry @spences10 ! I've got it installed globally but I'll forgotten to install it as a dev dependency for this project. Will do that now.

**Comment by MarcL** [comment]
Pull latest @spences10 and it should work. Shout if not.

**Comment by spences10** [comment]
Yeah, all good, thanks @MarcL 👍 

![image](https://cloud.githubusercontent.com/assets/234708/26056150/f954bb86-396b-11e7-9a6b-fe78c9efb1bb.png)
